// ═══════════════════════════════════════════════════════════════
//  LANGUAGE DATABASE
// ═══════════════════════════════════════════════════════════════
const LANG = {

  en: {
    appTitle:    "Cosmic Almanac",
    appSub:      "Your personal oracle — calibrated to the stars, the moon, and the particular chaos of being you.",
    obH2:        "Begin your reading",
    obP:         "Enter your birthday once. Your stars do the rest.",
    obLbl:       "Your date of birth",
    obBtn:       "✦  Reveal My Destiny",
    oracleLbl:   "✦  Today's Oracle",
    sugLbl:      "Cosmic Suggestion",
    changeBtn:   "Change birthday",
    detailClose: "Close details",
    resetMsg:    "Reset your birthday? The stars will need to meet you again.",
    confirmOk:   "Reset",
    confirmCancel:"Keep it",
    langToggle:  "Chinese",
    creatorBtn:  "Creator: meltcado 🥑",
    creatorKicker:"Creator",
    creatorTitle:"Why Meltcado 😜",
    creatorCopy: "Because avocados always feel like they are quietly on the edge of melting.",
    prevDay:     "Previous",
    nextDay:     "Next",
    todayBtn:    "Today",
    detailRhythm:"Today's rhythm",
    detailWatch: "Watch for",
    detailMove:  "One small move",
    readingTitles:["Your Daily Reading","The Stars Speak","Today's Oracle","Cosmic Forecast","The Universe Weighs In"],
    yearOf:      a => `Year of the ${a}`,
    dateStr:     (wday,m,d,y) => `${wday}, ${m} ${d}, ${y}`,
    dayNames:    ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],
    monthNames:  ["January","February","March","April","May","June","July","August","September","October","November","December"],
    moonNames:   ["New Moon","Waxing Crescent","First Quarter","Waxing Gibbous","Full Moon","Waning Gibbous","Last Quarter","Waning Crescent"],
    westNames:   ["Capricorn","Aquarius","Pisces","Aries","Taurus","Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius"],
    chiNames:    ["Rat","Ox","Tiger","Rabbit","Dragon","Snake","Horse","Goat","Monkey","Rooster","Dog","Pig"],
    zodiacNames: ["Aries","Taurus","Gemini","Cancer","Leo","Virgo","Libra","Scorpio","Sagittarius","Capricorn","Aquarius","Pisces"],
    planetNames: ["Sun","Moon","Mars","Mercury","Jupiter","Venus","Saturn"],
    aspectNames: {conjunction:"conjunct",trine:"trine",sextile:"sextile",square:"square",opposition:"opposite",neutral:""},
    rLbls:       ["","Rough Waters","Murky Skies","Clear Skies","Fair Winds","Star Aligned"],
    work:{
      name:"Work & Career",
      m:{
        1:["The cosmic gears are jammed today. Submit nothing important, sign nothing legally binding, and avoid your boss if at all possible.",
           "Your productivity has the energy of a browser with 47 tabs open. Close some tabs. Maybe close your laptop.",
           "Mercury is in retrograde energy — even if it isn't. Your ideas are fine; the timing is genuinely not.",
           "Today the stars vote for strategic invisibility. Be the human equivalent of 'on a call.'",
           "The planets have arranged themselves specifically to complicate your professional life today. Nothing personal — they do this sometimes.",
           "Career energy today: dial tone. Show up, be polite, and do not volunteer for anything.",
           "The cosmic forecast suggests that anything you start today will take twice as long and go sideways. Begin nothing.",
           "Professional instincts are muffled today. When in doubt, do less. The universe will explain itself later.",
           "Ambition is admirable. Today, however, ambition is also inadvisable. Rest the professional engine.",
           "The stars have reviewed your calendar and quietly suggested you cancel half of it.",
           "Communication at work carries extra static today. Confirm everything twice and send nothing in anger.",
           "Low-output days are not wasted days. The stars are filing this one under 'necessary recovery.'"],
        2:["Minor celestial friction in your career lane. Push through carefully — the path clears by afternoon.",
           "The stars aren't against you today, they're just… indifferent. Same as your coworkers. You'll survive.",
           "Your work energy is at 60%. Fortunately, most things only need 60%.",
           "One step forward, one step sideways. The universe is teaching you the cha-cha of professional life.",
           "Small delays and mild misunderstandings are on the cosmic menu today. Order patience instead.",
           "Progress is happening — just slowly enough to be annoying. Trust the accumulation.",
           "The professional winds are light and variable. Tack carefully and you'll get where you're going.",
           "Not your finest day at the office, but not your worst either. The stars log this as 'adequate.'",
           "Cosmic headwinds today are mild. They won't stop you, but they'll require more effort than usual.",
           "Work requires a little more elbow grease than normal. The resistance is temporary.",
           "Your ideas are sound; today's execution may just need a few more revisions than planned.",
           "The universe is asking for patience in your career lane. You'll understand why by Thursday."],
        3:["A steady, unremarkable day at work. The universe calls this 'acceptable.' So do most performance reviews.",
           "No great breakthroughs, no disasters. The cosmic middle ground — which is honestly underrated.",
           "Solid. Functional. Mildly caffeinated. A perfectly serviceable work day with cosmic backing.",
           "The stars see average output and are totally at peace with that. Not every day needs to be legendary.",
           "Competent, consistent, unremarkable. The foundation of every actual career. The stars nod approvingly.",
           "Today's professional energy is like good weather — you only notice it when it's gone.",
           "Business as usual. The cosmos have filed no complaints. Neither should you.",
           "A dependable, workmanlike day. Not the stuff of highlight reels, but quietly essential.",
           "The cosmic ledger shows your work column in balance. Nothing gained dramatically, nothing lost.",
           "Neutral professional energy. All systems nominal. Complete the ordinary tasks with full attention.",
           "The stars see you doing the work. They don't find it glamorous, but they respect it.",
           "Middle-of-the-road professional day. The path is clear and well-maintained. Walk it steadily."],
        4:["The cosmic current carries your career forward. Push on anything you've been hesitating about.",
           "Good energy flows through your professional life. The stars are watching with quiet approval.",
           "You're operating with unusual clarity today. Use it. The universe doesn't always pick up when you call.",
           "Decisions made today have solid cosmic backing. Trust your professional instincts.",
           "Your professional frequency is elevated. The ideas landing today are genuinely good — act on them.",
           "Something is opening in your career lane. The stars can't say exactly what yet, but they're pointing at it.",
           "Unusually sharp focus today. The kind you can't force — use it while it lasts.",
           "People in power are receptive to you today. Say the thing. Ask for the thing. The timing is real.",
           "Career momentum is available. Apply force in the right direction and watch things move.",
           "The stars have cleared turbulence from your professional path. Cruise efficiently.",
           "Collaborative energy is high. The project that needs other people — start it today.",
           "Your credibility carries extra weight today. Show your work and let it speak."],
        5:["The stars have cleared your lane entirely. Everything you touch today has a touch of gold — don't waste it.",
           "Cosmic alignment: maximum. Your professional presence today is genuinely formidable. Let people know.",
           "You were born for days like this. Swing big. Say the brave thing in the meeting. Sign things.",
           "The universe has put every celestial body in your corner. This is not a drill.",
           "Peak career day. The planets have conspired on your behalf. Repay them by doing something worthy of it.",
           "Your professional star is blazing today. Walk into every room like you know exactly where you're going.",
           "Everything is working. Every tool, every relationship, every instinct — in alignment. Go.",
           "The cosmos are open for business in your name today. Negotiate hard. Launch things. Ask for more.",
           "Career peak achieved. The universe has given you the momentum — your only job is not to overthink it.",
           "Strategic moves made today have cosmic amplification. Think big, then act.",
           "Today your reputation precedes you in the best possible way. Let it do its job.",
           "The stars have written your name in the professional sky today. Make sure your output is worthy of the billing."]
      }
    },
    love:{
      name:"Love & Social",
      m:{
        1:["The love stars are taking a personal day. Keep interactions brief, texts short, and feelings to yourself for now.",
           "Today's social energy is like Wi-Fi in a basement. Connection keeps dropping. It's not you. It's the universe.",
           "Best romantic move today: make yourself tea, watch something comforting, and lower your social expectations significantly.",
           "Avoid deep conversations today. The cosmos haven't finished buffering your emotional software.",
           "The social sky is overcast. Not stormy — just grey. People may be harder to read than usual. Don't push.",
           "Venus is not cooperating today. Love energy is low and connection feels like work. Reserve your emotional budget.",
           "Miscommunication is possible today. Say less, listen more, and hold off on the difficult conversations.",
           "The love department is temporarily closed for maintenance. You can reopen it tomorrow.",
           "Your social antennae are slightly off today. The signals you're reading may not be the signals being sent.",
           "Solitude is not loneliness. The stars see you alone today and call it 'recharging.' So should you.",
           "Today is for protecting your own peace, not for expanding connections. The people who matter will still be there tomorrow.",
           "Emotional static is high today. Even good relationships may feel misaligned. Breathe and wait."],
        2:["A mildly awkward social frequency surrounds you. Lean into it — awkward can be charming when fully committed.",
           "Love is present but slightly blurry, like a photo taken too fast. Wait for the focus to return.",
           "Your social energy needs a gentle warm-up. Start with something low-stakes before anything meaningful.",
           "Connection attempts may require more effort than usual today. Persistence is your friend.",
           "Romantic energy is muted but present. A small, quiet gesture beats a grand one today.",
           "Social interactions are functional but not sparkling. That's fine — not every interaction needs to be electric.",
           "The warmth is there, just buried a little. Some excavation required.",
           "Friendships and relationships feel slightly out of sync today. Give things time to find their rhythm.",
           "Love today is a small flame, not a bonfire. Protect it from the wind rather than fanning it.",
           "The connections you need are closer than they seem — you may just need to reach slightly further than usual.",
           "Social energy is below the waterline but rising. By evening, the tide will have shifted.",
           "People are slightly harder to reach today. Don't take it personally — the universe is running slow."],
        3:["Warm, comfortable social energy. Nothing fireworks, nothing cold. A perfectly pleasant human day.",
           "Your social life today is like background music — pleasant, stable, easy to overlook. That's genuinely fine.",
           "Connections made today are solid if unspectacular. Quality over cosmic drama.",
           "The social weather is mild and agreeable. Show up for the people who matter.",
           "Good middle-ground energy for relationships. Steady, reliable, and quietly nourishing.",
           "Companionship is available. The people you love are accessible. Nothing extraordinary — just real.",
           "Social interactions have a comfortable, low-pressure quality today. Exactly what most relationships need most.",
           "The love department is open for routine business. Nothing epic, but everything genuine.",
           "Ordinary connection is still connection. Today's relationships are nourishing without being dramatic.",
           "A pleasant social cadence today. Follow it without overthinking. The cosmos call this 'good enough.'",
           "Warmth is exchanged in quiet ways today. A text, a laugh, a shared moment. These count.",
           "The stars observe your social life today with mild contentment. Everything where it should be."],
        4:["Your warmth is magnetic today. The people in your orbit feel it — let them feel it fully.",
           "Good social energy flows freely. Reach out to someone you've been meaning to. Now is genuinely the time.",
           "Romance has a favorable current today. Something small and genuine goes further than you'd expect.",
           "You're unusually good company today. The stars have made a note of it.",
           "Love energy is elevated. The things you say today will be remembered. Choose them with care.",
           "Your presence carries extra warmth today. People lean toward you without knowing why.",
           "A favorable day for meaningful conversations — the ones you keep putting off. The conditions are right.",
           "Social luck is on your side. The person you reach out to will be glad you did.",
           "Something beautiful is available in your relationships today. You'll recognize it when it arrives.",
           "The right words come easily today. Use them. Someone in your life needs to hear them.",
           "Romantic energy is active and favorable. A small gesture carries the weight of a large one.",
           "Love is easy today — which is rarer than it sounds. Don't let it slip past unnoticed."],
        5:["Maximum heart energy. The stars have essentially written 'go connect with people' across the sky in your name.",
           "You are irresistible to the right people today. The universe has scheduled at least one meaningful moment.",
           "Love is loud today — romantic, friendly, or self-directed. Open every door when it knocks.",
           "The cosmos have aligned your social frequency to its peak. Say the things that matter.",
           "Full love frequency. The kind of day where the universe cooperates and people actually show up.",
           "Romantic peak. If there is something left unsaid, today the stars have cleared the path to say it.",
           "Your social energy today is contagious. Everyone in your orbit benefits from your presence.",
           "Connection is effortless today — which means you owe it to yourself and others to actually show up.",
           "Love is available in every form today. Accept it in all directions. Give it freely.",
           "The stars have engineered a perfect window for the relationship conversation you've been circling. Use it.",
           "Your magnetism is at its highest. The universe has cleared the social skies and is pointing at you.",
           "Today the heart is loud, clear, and brave. Say what you mean, feel what you feel, let people see it."]
      }
    },
    health:{
      name:"Health & Body",
      m:{
        1:["Your body is filing a formal complaint with the universe today. Listen to it. Rest is not weakness.",
           "Today is a good day to cancel something, drink water, and pretend you are a plant on a windowsill.",
           "The stars see low vitality in your physical lane. Honor it. Not every day is a workout day.",
           "Sleep. Eat something warm. Move gently. The cosmos will still be here when you feel better.",
           "Physical energy is at a low ebb. This is the universe's way of forcing the recovery you've been skipping.",
           "Your body is waving a small flag today. It is not asking for much — just some quiet and some water.",
           "The stars see fatigue and are compassionate about it. Today is not about doing more. It's about doing less.",
           "Low physical frequency today. This isn't failure — it's biology. Rest accordingly.",
           "Something in the planetary arrangement says: slow down, eat a real meal, and go to bed early.",
           "Your body needs you to be on its side today. Be on its side.",
           "The health channel is receiving minimal signal today. Quiet recovery is the only meaningful task.",
           "Honor the low. Bodies move in cycles. Today is the trough, and the peak will follow."],
        2:["Energy levels are slightly below par. Nothing a nap, some protein, and a gentle walk can't negotiate.",
           "Your body is asking for gentleness today. Obliging it is an act of wisdom, not surrender.",
           "Minor physical static today. The stars suggest: hydrate, breathe deeply, and pace yourself.",
           "Below-average vitality. The universe recommends you conserve what you have for what matters.",
           "Energy is available but should be rationed. Don't spend it on things that don't need it.",
           "Your physical engine is idling below normal today. Give it better fuel and let it warm up slowly.",
           "The body is slightly off-balance. Nothing serious — just in need of basic maintenance and consideration.",
           "Below-average health day. The answer is consistency, not heroics. Small, restorative choices only.",
           "Physical resilience is reduced slightly today. This is a signal, not a crisis.",
           "Mild physical drag in your orbit today. Nothing that gentleness and decent sleep won't resolve.",
           "The stars see a body running slightly warm — not hot. Ease the pressure and give it breathing room.",
           "Below optimal, but functional. Do what you must, skip what you can, and restore tonight."],
        3:["Steady health energy. Your body is humming along at a sensible rhythm. Keep it going.",
           "Nothing alarming, nothing euphoric. A good, functional body day — which is deeply underappreciated.",
           "Maintenance mode is valid mode. The stars see a balanced, steady you today.",
           "Your physical energy is where it should be. Routine and rhythm are your friends today.",
           "The body is cooperating. That's more than can be said for some days. Take it seriously.",
           "Physical baseline: solid. Nothing exceptional in either direction. This is what health looks like most days.",
           "The cosmic health reading is: normal. Normal is what you build peak days from.",
           "All physical systems operating within expected parameters. Enjoy the neutrality while it lasts.",
           "Stable, predictable, functioning health energy. The kind of day where you can actually get things done.",
           "The body is present and accounted for. Routine care will keep it that way.",
           "Nothing spectacular, nothing alarming. A body-day that works, which is quietly remarkable.",
           "The stars see you in reasonable shape today. Treat your body accordingly — with ordinary care and respect."],
        4:["Good vitality today. Your body wants to move. Let it.",
           "Physical energy is above average. If you've been postponing that walk or workout — do it now.",
           "Your health frequency is high today. Use it wisely. Your future self will remember this.",
           "The body is willing. The stars approve. Whatever you've been putting off physically — today's your day.",
           "Above-average physical energy. The kind of day where exercise feels like a reward instead of a duty.",
           "Your body is well-rested, well-fueled, and ready. Don't leave that on the table.",
           "Good health momentum today. Stack it with the right inputs and it compounds.",
           "The physical channel is running clear today. Take advantage of the signal while it's strong.",
           "Vitality is accessible. Your body will respond well to whatever you ask of it today.",
           "Health energy elevated. The stars specifically recommend using this window. It doesn't stay open.",
           "Your immune system, your muscles, your mind — all tracking above baseline today.",
           "High physical frequency. Lean into movement. Your body is telling you it wants to be used."],
        5:["Peak physical energy. Your body is a high-performance vehicle today. Drive it accordingly.",
           "The cosmic health chart shows excellent alignment. Today is the day you do the things you keep promising yourself.",
           "You feel it, don't you? That unusual lightness. The stars gave it to you. Use every bit of it.",
           "Everything is firing correctly today. This is rare. Move, breathe, feel alive. The stars insist.",
           "Maximum vitality. The kind of day your body has been quietly building toward. Make it count.",
           "Health peak achieved. Your physical energy today could power a small city. Redirect it usefully.",
           "The stars have handed you a fully-charged physical day. It would be a cosmic shame to waste it.",
           "Extraordinary health alignment. Your strength, your stamina, your focus — all at their highest.",
           "This is the rare, mythical 'feel amazing' day. Don't spend it on the couch. The stars are watching.",
           "Peak body day. Whatever physical goal you've been circling — today is the day to begin it in earnest.",
           "Vitality at maximum. Your body is asking to be pushed. Politely but firmly — push it.",
           "The physical universe has aligned in your favor today. Breathe deeply, move boldly, be undeniably alive."]
      }
    },
    finance:{
      name:"Finance & Luck",
      m:{
        1:["Today is not the day to gamble, invest aggressively, or buy anything non-essential. The money stars are napping.",
           "Hold your wallet close and your credit card closer. The financial cosmos have a mischievous glint today.",
           "Today's lucky number is 'no.' Apply it liberally to any financial decisions that arise.",
           "The universe recommends reviewing your subscriptions. One is definitely something you forgot you signed up for.",
           "The financial planets are in a complicated mood. The best investment today is inaction.",
           "Cosmic bad luck in the money lane. Don't test it. Every financial instinct you have today is probably wrong.",
           "Today is not for spending, not for investing, not for financial risk of any kind. Close the apps and wait.",
           "The money stars have dimmed. Something you buy today will feel like a mistake by Friday.",
           "Financial energy is at a low. Whatever the purchase, it can wait. Whatever the bet, pass on it.",
           "The universe has placed a gentle but firm hand on your wallet today. Respect the signal.",
           "Financial luck is below the floor today. This is not the day to test it. Stay completely still.",
           "Cosmic financial interference is high. Even good deals will have hidden costs today. Walk away."],
        2:["Modest financial energy. Spend only what's necessary. Save the big moves for when the stars are paying attention.",
           "Money flows slowly today — like water through a reluctant drain. Patience is the only currency worth spending.",
           "Below-average luck in the material realm. Gratitude for what you have is the best investment today.",
           "The financial forecast is cautious. Watch the small leaks — that's where it always goes.",
           "Financial energy is subdued but stable. Handle the basics and leave the ambition for a better day.",
           "Luck is running slightly low in the money department. Be conservative and patient.",
           "The investment or purchase you're considering can wait for a better cosmic window. This isn't it.",
           "Material luck is below par. Protect what you have. The right opportunity will come on a stronger day.",
           "Small financial friction today. Nothing dramatic — just a gentle reminder to be careful.",
           "Below-average fortune in the financial lane. This is a maintenance day, not a growth day.",
           "Cosmic luck in money matters is running thin today. Spend less, expect less, wait for more.",
           "The financial stars are distracted. Skip big decisions and tend to the small, sensible ones instead."],
        3:["Financial neutrality today. Money is where you left it, doing what you told it to do. Stable counts.",
           "Luck is present but modest. Small wins, small losses — the universe balancing its books today.",
           "Average financial day. Nothing dramatic. This is actually fine. Not every day needs to be a money day.",
           "Steady financial weather. No surprises expected. Routine management is the move.",
           "Middle-ground financial energy. No windfalls, no disasters. The cosmic ledger breaks even today.",
           "Financial luck is neutral. Neither favored nor hindered — which means skill matters more than chance.",
           "A routine money day. Pay what's due, save what's possible, and don't read too much into it.",
           "The financial cosmos are calm today. Calm is often underappreciated as a financial condition.",
           "Steady material energy. No cosmic turbulence. The money you manage carefully will stay managed.",
           "An average luck day in the material realm. Make deliberate choices and leave chance out of it.",
           "Financial middle ground. The stars aren't amplifying anything today — it's all you from here.",
           "The money stars are balanced today. Nothing moving dramatically in either direction. Hold steady."],
        4:["Your financial luck is quietly strong today. Small opportunities may look unimportant. Look closer.",
           "Good energy in the money lane. Decisions made now have solid cosmic backing.",
           "The stars smile on your financial awareness today. Act on the thing you've been quietly considering.",
           "Above-average luck in the material realm. Keep your eyes open — something is worth noticing.",
           "Financial momentum is building in your favor. Keep your eyes open and your instincts sharp.",
           "Lucky window in the money sector. Small, well-timed moves can have outsized results today.",
           "Above-average material luck. The thing you've been cautious about may now be worth attempting.",
           "The financial stars are generous but quiet today. They reward attention, not wishful thinking.",
           "Good luck energy in the money lane. Act with intention and the universe will amplify it.",
           "Material fortune is elevated. A specific opportunity is in your path today — don't walk past it.",
           "Financial favor is with you. The instinct you've been second-guessing may actually be right.",
           "Above-average cosmic backing in the material realm. Make the call. Execute the plan."],
        5:["Lucky streak. The universe is pointing arrows at financial opportunities today. Stay awake to it.",
           "Peak financial alignment. If you've been waiting for a sign — there it is, written in the stars.",
           "Cosmic good fortune in your material lane. Not lottery-win magnitude — but meaningfully good. Don't waste it.",
           "The money stars are singing your name today. Act with intention. The window is real.",
           "Maximum financial alignment. Whatever you've been preparing for — today is the day to act.",
           "The universe has opened a genuine financial window. Walk through it deliberately and without hesitation.",
           "Lucky peak in the material realm. The stars have handed you favorable odds. Play them wisely.",
           "Financial fortune at its highest. A bold but calculated move made today has cosmic amplification.",
           "The planetary alignment today is unusually favorable for material gains. Don't leave opportunity on the table.",
           "Peak financial energy. Your instincts in the money lane are sharp and the conditions are cooperating.",
           "The financial stars are at full power in your chart today. Move with confidence and precision.",
           "Cosmic jackpot alignment. Not guaranteed — but the conditions for significant financial progress are rare and present."]
      }
    },
    oracles:[
      "The universe has a soft spot for you today. It's subtle — in the way the coffee tastes just right, the light a little kinder, the timing strangely perfect.",
      "Something small and good is coming your way today. You won't see it coming, which is entirely the point.",
      "The stars are rooting for you with quiet, genuine enthusiasm. Not loudly — just steadily, in the background, like a very loyal friend.",
      "Today holds a small miracle somewhere in it. It might be a conversation, a moment of clarity, or finally finding where you left your keys.",
      "You are exactly where you are supposed to be today. Trust the strange, winding path. It's going somewhere worthwhile.",
      "The cosmos have reviewed your recent decisions and, despite everything, have given you a passing grade. Well done for surviving yourself.",
      "Today the universe has scheduled a 'mild inconvenience' for character building. It's not personal. The stars do this to everyone they like.",
      "Mercury is currently behaving itself. Everyone is surprised, including Mercury. Make hay while the planets align.",
      "The celestial committee has approved your continued existence today. Try not to make them regret it.",
      "Your horoscope for today: things will happen, you will feel things about them, and somehow it will work out. Groundbreaking.",
      "The stars have been observing your life for some time now. They find it compelling. Not always in a reassuring way — but compelling nonetheless.",
      "Somewhere in the universe, a star died to create the atoms in your coffee. The least you can do is enjoy it slowly.",
      "The moon looked at your chart and exhaled slowly. Then it said 'you've got this.' It sounded almost entirely convincing.",
      "Today you will age exactly one day. The stars consider this non-negotiable. On the bright side, so does everyone else.",
      "The universe doesn't actually care about your problems — it has 93 billion light-years of its own. And yet somehow, things tend to work out. Keep going.",
      "In the grand cosmic scheme, today is statistically insignificant. In the small human scheme, it could be the day everything shifts. Worth showing up for.",
      "Your ancestors survived unimaginable things so you could worry about notifications. Honor them by putting your phone down for at least five minutes.",
      "The cosmos have been running this a long time. The thing you're worried about is usually not the actual thing.",
      "Today's energy is best described as: possible. Which, in the grand scale of the universe, is actually quite generous.",
      "The stars have reviewed the data and concluded: you are more capable than you currently believe. This is their official, unambiguous position.",
      "Chaos theory suggests that small decisions compound into large outcomes. Today's small decision matters. Choose deliberately.",
      "The moon is doing something beautiful tonight. Whether you see it or not, you are under the same sky as everyone you love.",
      "The universe has been alive for 13.8 billion years and hasn't quit once. You can get through today.",
      "A quiet power is building in your orbit today. The stars can't say exactly what it is — but they've noticed it, and so should you.",
      "The celestial forecast suggests unexpected warmth from an expected direction. The stars enjoy a good plot twist.",
      "Some days the stars align. Other days they're just doing their own thing and you happen to be in the same galaxy. Today is one of those days. Still valid.",
      "Your energy today is like a partial eclipse — not everything is illuminated, but what is visible is genuinely interesting.",
      "The universe filed a memo this morning: you are doing better than you think. The stars unanimously endorsed it.",
      "Today's cosmic frequency carries a specific instruction: rest without guilt. The stars know you need it and they are fine with it.",
      "Something in the planetary arrangement today whispers: be kinder to yourself than usual. The stars have noticed what you've been carrying.",
      "The planets are not conspiring against you today — they are simply indifferent, which is honestly much more manageable.",
      "You carry more than people see. The stars see it. That's worth something, even if it doesn't feel like it right now.",
      "Every version of you that got this far cleared impossible odds. The current version is doing fine.",
      "The cosmos have a long memory. They remember the version of you that kept going when it made no sense to. They're still impressed.",
      "Today's oracle: something you thought was finished is quietly not finished. Pay attention to the edges.",
      "The universe placed you in this exact time, with these exact circumstances, with these exact people. It is not random. It is not accidental.",
      "There is a version of today that goes beautifully. The stars aren't saying it's guaranteed — they're saying it's available.",
      "The celestial weather today is 'interesting' — which in cosmic terms means: something worth noticing is about to happen.",
      "You don't need to have everything figured out. The stars certainly don't, and they've been at this for billions of years.",
      "The thing you're building — the quiet, persistent, invisible thing — the stars see it. It is real and it is growing.",
      "Today the universe will present you with something in disguise. Patience is the only way to recognize it.",
      "Your resilience is not invisible. The cosmos have a dedicated file on it. It's thick.",
      "Not every day arrives with fanfare. Some of the best ones arrive quietly, dressed as ordinary Tuesdays.",
      "The stars have arranged something small and unexpectedly lovely for later today. Don't be looking the other way.",
      "You are someone's favorite person. The stars know who. You probably already know too.",
      "Today is a day that will matter in a way you can't yet see. Show up for it anyway.",
      "The universe operates on longer timescales than your anxiety does. It suggests you borrow some of that patience.",
      "There are people right now who are quietly grateful you exist. The stars have verified this.",
      "The cosmos note that you have survived every difficult day you've ever had. The current odds are therefore quite good.",
      "Today the universe offers you a small but genuine gift wrapped in something that looks like inconvenience. Open it.",
      "Your worry about the outcome is noted and filed. The stars recommend spending today on the process instead.",
      "The celestial bodies have been tracking your progress for some time. The trend is better than you're giving yourself credit for.",
      "Something that has been stuck is quietly beginning to move. The stars can feel the shift. You will too, shortly.",
      "The universe would like to remind you that the story isn't over. Not even close. Not even the halfway point.",
      "You are the product of every good decision and improbable coincidence that led to this moment. The stars find that extraordinary.",
      "Today holds at least one conversation worth having. The stars don't specify which — that's part of the deal.",
      "The moon has been watching you navigate hard things with more grace than you know. It's made a note of it.",
      "Not all growth is visible. Some of the most important kind looks like a quiet Tuesday where nothing seems to change.",
      "The stars have looked at where you're headed and have offered no objections. High cosmic praise.",
      "Something that felt like an ending is revealing itself to be a beginning. The stars appreciate dramatic irony.",
      "You are allowed to not have it all together today. The cosmos have factored this in and remain optimistic.",
      "Today's cosmic assignment: notice one thing you've been taking for granted. The stars believe this is the whole assignment.",
      "The universe has been patient with your timing. It would like you to be equally patient with its timing.",
      "Your instincts today are calibrated better than your doubts are. Trust the instinct.",
      "Something good is in motion. It is moving slowly, which is why you haven't noticed it yet. But it is moving.",
      "The stars have mapped every version of this day. The one where you try is consistently the best one.",
      "Today the universe is not asking for perfection. It is asking for presence. Manageable request.",
      "The cosmic record shows that you have made it through harder days than this. Today is filed under 'routine.'",
      "Something about today is different from yesterday in a way you haven't clocked yet. The stars have.",
      "The universe appreciates effort more than outcome. Today, effort is the whole game.",
      "You are not behind. There is no behind. There is only here, and here is exactly where you are supposed to be.",
      "The stars have arranged for at least one thing today to go better than expected. The arrangement has been confirmed.",
      "Whatever you are in the middle of — the middle is always the hardest part. You are in it. Keep going.",
      "Today the universe asks only that you show up as you are, not as you think you should be. As-is is enough.",
      "The celestial arrangement today carries a specific quality: things begun with good intentions will find good ends.",
      "Your story is still being written. Today is not the last page. It is not even close to the last page.",
      "The stars have observed your consistency. They find it quietly remarkable. Most people quit earlier than you do.",
      "Today holds more possibility than it advertises. Look past the obvious.",
      "The moon has a particular warmth for the version of you that keeps trying despite not knowing the outcome.",
      "The universe doesn't offer guarantees. But it offers today, and today contains enough.",
      "Something that felt impossible six months ago is now simply difficult. The stars note this as significant progress.",
      "Today the cosmic instruction is: do one small thing well. That is all. Just one small thing, done well.",
      "The universe is not grading you. It is observing you with curiosity and, when applicable, quiet admiration.",
      "There is a version of the future that looks very different from your current worry. The stars consider it more likely.",
      "Whatever you are carrying today — you are allowed to set some of it down. The stars will hold it while you rest.",
      "Today the stars offer a gentle reminder: being alive is the underrated part of the whole arrangement.",
      "The cosmos see what you are building. The fact that no one else sees it yet is not evidence that it isn't real.",
      "Today is a good day to remember: you have been wrong about yourself before — specifically, about how capable you are.",
      "The universe has no notes on how long things should take. Your timeline is entirely valid.",
      "The stars would like to point out that surviving this week counts as an achievement. They're marking it as such."
    ],
    suggestions:[
      "Send one message you've been overthinking. The overthinking is now the problem, not the message.",
      "Drink water before coffee. The stars said so. Ignore them and accept the consequences.",
      "Look up from your screen at least once per hour. The world is still out there, mildly and consistently beautiful.",
      "Tell one person something specific you appreciate about them. Vague compliments are cosmically weak.",
      "Cancel one thing you agreed to out of guilt. The universe approves this message.",
      "Eat something green today — not necessarily because it's healthy, just to remind yourself you run on real food.",
      "Take a walk without your phone. It's terrifying for exactly ninety seconds, then deeply pleasant.",
      "Write down three things, no matter how small. Your brain is a terrible filing system.",
      "Say no to something today. Once. Firmly. Without the essay of explanation.",
      "Sit outside for 10 minutes. The sky is doing something nice. It does this every day and most people miss it.",
      "Text someone you haven't spoken to in a while. Keep it short. 'Thinking of you' does more than you think.",
      "Clean one small thing — a surface, a drawer, your screenshots folder. The cosmos find clutter personally offensive.",
      "Buy yourself something small and nice. Not as a reward — just because you exist, and that's sufficient reason.",
      "Rest without guilt today. Horizontal ambition counts.",
      "Learn one completely useless thing. The internet is full of them. This is actually its best feature.",
      "Make your bed. Or don't. But notice how you feel about it at 9pm.",
      "Laugh at something stupid — fully, out loud. The stars specifically requested this.",
      "Eat lunch away from your desk. Revolutionary. Life-changing. Heavily endorsed by the cosmos.",
      "Do one thing you've been 'about to do' for more than three days. The universe is patiently waiting.",
      "Be kind to a stranger. Nothing elaborate — a door held, a smile, a brief acknowledgment of shared humanness.",
      "Put your phone in another room for one hour. Face the silence. Bargain with it. You'll eventually become friends.",
      "Stretch. You are not made of wood — even if it currently feels that way.",
      "Drink the fancy thing you've been saving. The stars genuinely don't understand what you're saving it for.",
      "Apologize if you need to. Not a 'sorry if you were offended' — an actual one.",
      "Watch the sunset, or at least acknowledge it's happening somewhere and that this is quietly beautiful.",
      "Make a list of everything you're avoiding. Then do the smallest item on it. This is how mountains move.",
      "Give someone your full attention for five minutes. No phone, no half-listening. Just presence.",
      "Compliment yourself once, out loud, not ironically. The stars are listening.",
      "Slow down by 20% today. Everything done at 80% speed gets done better. The math is somehow correct.",
      "Notice one beautiful thing before noon. Anything counts — a cloud, a color, the way light falls on something ordinary.",
      "Set one intention for today. Not a goal — an intention. There is a meaningful difference.",
      "Eat breakfast sitting down, away from your phone. The stars consider this a radical act of self-respect.",
      "Close five browser tabs you know you'll never read. The relief is disproportionate to the effort.",
      "Write down one thing you're grateful for. One is enough. The universe counts quality, not quantity.",
      "Take three slow, deliberate breaths before your first meeting. The stars have empirically validated this.",
      "Do the thing on your to-do list that has been there longest. It has outlived its welcome.",
      "Put on a song you haven't heard in years. Sit with it. Let it do what it does.",
      "Drink a full glass of water before you check your phone this morning. The cosmos demand this.",
      "Tell someone you love them, in whatever language is natural for you. Explicitly. Today.",
      "Take a different route somewhere today. New inputs create new thoughts. The universe endorses this.",
      "Light a candle, or open a window. Signal to yourself that this space is different from all other spaces.",
      "Eat slowly today. At least one meal. Taste it. The stars are tired of watching you inhale food.",
      "Forgive something small that you've been holding. Not for them — for the square footage it's taking up in you.",
      "Compliment a stranger. Keep it genuine, keep it brief. Then walk away. This is a perfect interaction.",
      "Call instead of texting. Just once. The human voice carries things that characters cannot.",
      "Do one thing with your hands today that doesn't involve a screen. Anything. The stars approve of anything.",
      "Go to bed 30 minutes earlier tonight. Your tomorrow self will file this under 'best decision of the week.'",
      "Read something on paper. Just a few pages. Your brain will remember how much it likes this.",
      "Step outside and look up at the sky. Not at the horizon — at the actual sky above you. It's bigger than you think.",
      "Write down one thing you want to stop carrying. Then consider what it would feel like to actually put it down.",
      "Do a favor for someone without announcing it. The invisible kind. The stars keep excellent records.",
      "Make a small decision you've been postponing. Pick something. Pick anything. The indecision costs more than the decision.",
      "Rearrange one small part of your space. Even a single object moved changes the energy of a room.",
      "Acknowledge something you did well this week. Not to anyone else — just to yourself. Accurately.",
      "Plan one thing to look forward to, no matter how small. The anticipation is half the value.",
      "Spend five minutes doing absolutely nothing. Not scrolling. Not thinking productively. Nothing. The stars insist.",
      "Listen to rain, or running water, or birds, or any sound that isn't human-made, for at least two minutes.",
      "Say thank you to someone whose work you usually take for granted. Sincerely. Specifically.",
      "Buy someone else's coffee today — a stranger's. For no reason. This is the kind of thing the stars live for.",
      "Clean out your email inbox by at least ten messages. The digital clutter is real clutter. Treat it as such.",
      "Write a sentence about how you feel today. Just one. The act of naming it does something useful.",
      "Cook something simple from scratch today. The act of making your own food changes your relationship to eating it.",
      "Send a voice message instead of a text, just once. It carries warmth that words on a screen cannot.",
      "Notice your posture right now and adjust it. Your future spine will file a formal note of appreciation.",
      "Put fresh flowers or a plant somewhere you look often. Living things in your space change your space.",
      "Make one decision today based on what you actually want, not what seems most practical.",
      "Close all the apps you're not using. Treat your phone like a tool, not a habit.",
      "Write down one thing you want to try in the next month. Schedule a first step for it.",
      "Do something nice for your future self before noon — prep food, lay out clothes, clear your desk.",
      "Ask for help with something today. You will find the experience less uncomfortable than you currently predict.",
      "Walk somewhere you would normally drive or take transit. If possible. If not, find a slightly longer route.",
      "Say something kind about someone behind their back. On purpose. It changes the atmosphere you carry.",
      "Identify the task you're most avoiding and do just the first two minutes of it.",
      "Take a photo of something beautiful today — not for anyone else. Just to see it properly.",
      "Eat dinner without any screen. Just the food and whatever else is happening in the room.",
      "Do a complete digital declutter of one folder or one app. The thoroughness is the point.",
      "Write down three things about yourself that you actually like. Accurate ones, not aspirational ones.",
      "Reach out to one person who made a difference to you and tell them specifically how.",
      "Give yourself a proper lunch break. Sit down, eat something real, and do nothing else for 20 minutes.",
      "Set a bedtime for tonight and actually keep it. One night of proper sleep is a meaningful investment.",
      "Find one thing you own that you no longer need and let it go.",
      "Notice something that's working well in your life right now. Spend a full minute with that thought.",
      "Say yes to something small and spontaneous today. The kind of thing you'd normally politely decline.",
      "Tidy one corner of your home thoroughly. Not the whole thing — just one corner, properly done.",
      "Take five deep breaths before your first coffee. The order matters.",
      "Write down one boundary you need to keep this week. Then keep it.",
      "Do something creative today, even badly — draw, write, hum, arrange. Output matters more than quality.",
      "Let a compliment land today. Don't deflect it. Just say thank you and let yourself believe it.",
      "Pick one thing off your plate that you've been doing for someone else's approval and decide if it still belongs.",
      "Spend ten minutes outside with no agenda. Not walking for exercise. Not sitting with a task. Just outside."
    ]
  }
};

const DETAILS = {
  en: {
    labels: {
      western: "Western Zodiac",
      chinese: "Chinese Zodiac",
      phase: "Moon Phase",
      moonSign: "Moon In Sign",
      planet: "Planetary Day",
      astro: "Astrology Snapshot",
      section: "Today's Reading",
      oracle: "Today's Oracle",
      suggestion: "Cosmic Suggestion"
    },
    western: [
      {
        range: "March 21 - April 19",
        facts: ["Element: Fire", "Mode: Cardinal", "Traits: bold, direct, initiating"],
        summary: "Aries is the ignition spark of the zodiac. It likes momentum, challenge, and being first through the door.",
        extra: "Typical Aries energy is brave, impatient, competitive, and refreshingly honest when it is balanced.",
        moonFocus: "When the moon moves through Aries, the day feels faster, sharper, and more action-oriented than usual.",
        notable: "Examples: Lady Gaga, Maya Angelou, Thomas Jefferson."
      },
      {
        range: "April 20 - May 20",
        facts: ["Element: Earth", "Mode: Fixed", "Traits: steady, sensual, loyal"],
        summary: "Taurus is the stabilizer sign. It values comfort, reliability, beauty, and anything built to last.",
        extra: "Typical Taurus energy is grounded, patient, stubborn, and very tuned to the physical world.",
        moonFocus: "When the moon moves through Taurus, people often want calm, consistency, good food, and less chaos.",
        notable: "Examples: Adele, David Attenborough, Queen Elizabeth II."
      },
      {
        range: "May 21 - June 20",
        facts: ["Element: Air", "Mode: Mutable", "Traits: curious, witty, adaptable"],
        summary: "Gemini is the messenger sign. It thrives on ideas, conversation, variety, and quick mental movement.",
        extra: "Typical Gemini energy is bright, social, restless, and excellent at noticing patterns and possibilities.",
        moonFocus: "When the moon moves through Gemini, the mood becomes more talkative, mobile, and mentally busy.",
        notable: "Examples: Angelina Jolie, Prince, John F. Kennedy."
      },
      {
        range: "June 21 - July 22",
        facts: ["Element: Water", "Mode: Cardinal", "Traits: protective, intuitive, loyal"],
        summary: "Cancer is the caretaker sign. It is deeply connected to home, memory, family, emotional safety, and instinct.",
        extra: "Typical Cancer energy is gentle on the outside, strong underneath, and highly aware of what people feel but do not say.",
        moonFocus: "When the moon moves through Cancer, feelings, home life, closeness, and self-protection come to the front.",
        notable: "Examples: Princess Diana, Frida Kahlo, Nelson Mandela."
      },
      {
        range: "July 23 - August 22",
        facts: ["Element: Fire", "Mode: Fixed", "Traits: radiant, confident, generous"],
        summary: "Leo is the solar sign of visibility and heart. It wants life to feel creative, vivid, and fully lived.",
        extra: "Typical Leo energy is expressive, warm, proud, and naturally drawn to courage, play, and leadership.",
        moonFocus: "When the moon moves through Leo, people often want more attention, joy, drama, and creative expression.",
        notable: "Examples: Barack Obama, Madonna, Neil Armstrong."
      },
      {
        range: "August 23 - September 22",
        facts: ["Element: Earth", "Mode: Mutable", "Traits: precise, thoughtful, practical"],
        summary: "Virgo is the sign of refinement. It notices details, wants systems to work, and prefers improvement over noise.",
        extra: "Typical Virgo energy is observant, helpful, discerning, and sometimes a little too aware of what still needs fixing.",
        moonFocus: "When the moon moves through Virgo, the day leans toward order, useful effort, and cleaning up loose ends.",
        notable: "Examples: Beyonce, Keanu Reeves, Mother Teresa."
      },
      {
        range: "September 23 - October 22",
        facts: ["Element: Air", "Mode: Cardinal", "Traits: diplomatic, elegant, balancing"],
        summary: "Libra is the relationship sign. It seeks harmony, fairness, proportion, and beauty between people.",
        extra: "Typical Libra energy is charming, strategic, idealistic, and always trying to improve the tone of the room.",
        moonFocus: "When the moon moves through Libra, connection, aesthetics, compromise, and social awareness become stronger themes.",
        notable: "Examples: Serena Williams, Mahatma Gandhi, Oscar Wilde."
      },
      {
        range: "October 23 - November 21",
        facts: ["Element: Water", "Mode: Fixed", "Traits: intense, perceptive, loyal"],
        summary: "Scorpio is the depth sign. It is drawn to truth, power, transformation, and the things people usually keep hidden.",
        extra: "Typical Scorpio energy is magnetic, private, all-in, and difficult to fool once it has locked onto something real.",
        moonFocus: "When the moon moves through Scorpio, feelings intensify and people tend to crave honesty over surface politeness.",
        notable: "Examples: Marie Curie, Leonardo DiCaprio, Indira Gandhi."
      },
      {
        range: "November 22 - December 21",
        facts: ["Element: Fire", "Mode: Mutable", "Traits: adventurous, candid, expansive"],
        summary: "Sagittarius is the horizon sign. It wants movement, meaning, freedom, and a bigger view of life.",
        extra: "Typical Sagittarius energy is optimistic, blunt, funny, and always looking for the next idea, road, or revelation.",
        moonFocus: "When the moon moves through Sagittarius, the day feels more restless, direct, playful, and future-facing.",
        notable: "Examples: Jane Austen, Winston Churchill, Taylor Swift."
      },
      {
        range: "December 22 - January 19",
        facts: ["Element: Earth", "Mode: Cardinal", "Traits: disciplined, ambitious, reliable"],
        summary: "Capricorn is the builder sign. It respects time, mastery, accountability, and results that hold their shape.",
        extra: "Typical Capricorn energy is composed, strategic, dryly funny, and very good at carrying responsibility.",
        moonFocus: "When the moon moves through Capricorn, the emotional tone becomes more measured, practical, and goal-aware.",
        notable: "Examples: Michelle Obama, Isaac Newton, Martin Luther King Jr."
      },
      {
        range: "January 20 - February 18",
        facts: ["Element: Air", "Mode: Fixed", "Traits: independent, inventive, future-minded"],
        summary: "Aquarius is the visionary sign. It is interested in systems, ideas, originality, and what comes next.",
        extra: "Typical Aquarius energy is unconventional, humane, cerebral, and slightly detached in order to see the bigger pattern.",
        moonFocus: "When the moon moves through Aquarius, the day favors fresh thinking, distance, objectivity, and unusual connections.",
        notable: "Examples: Oprah Winfrey, Charles Darwin, Abraham Lincoln."
      },
      {
        range: "February 19 - March 20",
        facts: ["Element: Water", "Mode: Mutable", "Traits: imaginative, compassionate, intuitive"],
        summary: "Pisces is the dream and empathy sign. It is tuned to feeling, symbolism, imagination, and what cannot be measured cleanly.",
        extra: "Typical Pisces energy is tender, creative, absorbent, and often more affected by atmosphere than it first appears.",
        moonFocus: "When the moon moves through Pisces, intuition, softness, creativity, and emotional permeability all increase.",
        notable: "Examples: Rihanna, Albert Einstein, Ruth Bader Ginsburg."
      }
    ],
    chinese: [
      {
        cycle: "Repeats every 12 years",
        facts: ["Tone: quick, strategic, adaptable", "Strength: finding openings", "Shadow: overthinking or scheming"],
        summary: "Rat years are associated with alertness, intelligence, and knowing how to move early when an opportunity appears.",
        extra: "People linked with Rat energy are often resourceful, socially observant, and surprisingly effective under pressure.",
        notable: "Examples: Scarlett Johansson, Mark Zuckerberg, Prince Harry."
      },
      {
        cycle: "Repeats every 12 years",
        facts: ["Tone: steady, patient, dependable", "Strength: endurance", "Shadow: rigidity or slowness to pivot"],
        summary: "Ox energy is about strength through consistency. It prefers substance over flash and effort over noise.",
        extra: "People linked with Ox energy often come across as calm, disciplined, stubborn, and quietly formidable.",
        notable: "Examples: Barack Obama, Vincent van Gogh, Margaret Thatcher."
      },
      {
        cycle: "Repeats every 12 years",
        facts: ["Tone: bold, instinctive, magnetic", "Strength: courage", "Shadow: impulsiveness or pride"],
        summary: "Tiger years are associated with risk, charisma, and a strong personal presence that dislikes being boxed in.",
        extra: "People linked with Tiger energy are often brave, dramatic, protective, and energized by challenge.",
        notable: "Examples: Queen Elizabeth II, Lady Gaga, Leonardo DiCaprio."
      },
      {
        cycle: "Repeats every 12 years",
        facts: ["Tone: graceful, diplomatic, intuitive", "Strength: reading the room", "Shadow: avoidance of conflict"],
        summary: "Rabbit energy is gentle on the surface but sharp underneath. It values peace, taste, and emotional intelligence.",
        extra: "People linked with Rabbit energy are often tactful, artistic, soothing, and sensitive to atmosphere.",
        notable: "Examples: Albert Einstein, Angelina Jolie, David Beckham."
      },
      {
        cycle: "Repeats every 12 years",
        facts: ["Tone: charismatic, ambitious, vivid", "Strength: commanding attention", "Shadow: intensity or excess"],
        summary: "Dragon years are traditionally seen as powerful, lucky, and larger than life. This is the mythic sign of force and presence.",
        extra: "People linked with Dragon energy are often confident, dynamic, dramatic, and hard to ignore.",
        notable: "Examples: Bruce Lee, Rihanna, Salvador Dali."
      },
      {
        cycle: "Repeats every 12 years",
        facts: ["Tone: analytical, enigmatic, elegant", "Strength: strategy", "Shadow: secrecy or suspicion"],
        summary: "Snake energy is thoughtful, self-contained, and excellent at reading motives beneath the surface.",
        extra: "People linked with Snake energy are often perceptive, stylish, private, and very deliberate about their moves.",
        notable: "Examples: J.K. Rowling, Taylor Swift, Bob Dylan."
      },
      {
        cycle: "Repeats every 12 years",
        facts: ["Tone: spirited, freedom-loving, lively", "Strength: momentum", "Shadow: impatience or restlessness"],
        summary: "Horse years are associated with independence, movement, and a dislike of anything that feels confining.",
        extra: "People linked with Horse energy are often expressive, sociable, capable, and at their best when they can move freely.",
        notable: "Examples: Nelson Mandela, Paul McCartney, Aretha Franklin."
      },
      {
        cycle: "Repeats every 12 years",
        facts: ["Tone: gentle, artistic, compassionate", "Strength: emotional sensitivity", "Shadow: hesitation or worry"],
        summary: "Goat energy is soft, imaginative, and often more resilient than it first appears. It values beauty and emotional warmth.",
        extra: "People linked with Goat energy are often caring, creative, refined, and highly affected by environment.",
        notable: "Examples: Steve Jobs, Julia Roberts, Mark Twain."
      },
      {
        cycle: "Repeats every 12 years",
        facts: ["Tone: clever, inventive, playful", "Strength: improvisation", "Shadow: trickiness or inconsistency"],
        summary: "Monkey years are associated with intelligence, curiosity, and a strong instinct for hacking the system creatively.",
        extra: "People linked with Monkey energy are often witty, adaptable, restless, and unusually good at solving problems on the fly.",
        notable: "Examples: Tom Hanks, Celine Dion, Elizabeth Taylor."
      },
      {
        cycle: "Repeats every 12 years",
        facts: ["Tone: sharp, precise, self-possessed", "Strength: standards", "Shadow: criticism or perfectionism"],
        summary: "Rooster energy values clarity, polish, and saying the thing directly instead of pretending everything is fine.",
        extra: "People linked with Rooster energy are often articulate, stylish, disciplined, and very aware of presentation.",
        notable: "Examples: Beyonce, Roger Federer, Jennifer Aniston."
      },
      {
        cycle: "Repeats every 12 years",
        facts: ["Tone: loyal, honest, protective", "Strength: trustworthiness", "Shadow: defensiveness or worry"],
        summary: "Dog years are associated with integrity, duty, and strong instincts about who or what deserves protection.",
        extra: "People linked with Dog energy are often dependable, sincere, service-minded, and slow to abandon the people they love.",
        notable: "Examples: Winston Churchill, Madonna, Mother Teresa."
      },
      {
        cycle: "Repeats every 12 years",
        facts: ["Tone: generous, warm, comfort-loving", "Strength: abundance mindset", "Shadow: indulgence or naivety"],
        summary: "Pig energy is open-hearted, sociable, and often connected with pleasure, generosity, and enjoying life fully.",
        extra: "People linked with Pig energy are often kind, candid, optimistic, and more resilient than their softness suggests.",
        notable: "Examples: Stephen King, Alfred Hitchcock, Hillary Clinton."
      }
    ],
    phases: [
      {
        subtitle: "The reset point of the lunar cycle",
        facts: ["Window: start of the cycle", "Theme: beginnings, intention, blank space"],
        summary: "The new moon is the dark moon. It is the quietest phase, often associated with seeds, resets, and private starts.",
        extra: "This phase is less about public results and more about setting direction before anything is fully visible."
      },
      {
        subtitle: "The first slim crescent after the new moon",
        facts: ["Window: early growth", "Theme: momentum, courage, first moves"],
        summary: "Waxing Crescent is the part of the cycle where intention begins turning into action. It is small, visible, and still building.",
        extra: "This phase usually carries trial energy: start, test, adjust, continue."
      },
      {
        subtitle: "Half-lit moon, roughly one week in",
        facts: ["Window: first major checkpoint", "Theme: action, friction, decision"],
        summary: "First Quarter energy is about commitment. The moon is gaining light, but effort and course correction matter here.",
        extra: "This phase often feels decisive because you can no longer stay only in planning mode."
      },
      {
        subtitle: "Almost full, still building",
        facts: ["Window: pre-peak", "Theme: refinement, preparation, momentum"],
        summary: "Waxing Gibbous energy is growth with pressure. Things are filling out, and attention shifts toward improvement and timing.",
        extra: "This phase often asks for patience, edits, and one more round of effort before the reveal."
      },
      {
        subtitle: "The brightest, most visible phase",
        facts: ["Window: midpoint peak", "Theme: culmination, clarity, emotional volume"],
        summary: "Full Moon energy is the peak of the cycle. What was building becomes visible, loud, or impossible to ignore.",
        extra: "This phase is often linked with heightened feeling, illumination, endings, and public realization."
      },
      {
        subtitle: "Just after the full moon",
        facts: ["Window: early release", "Theme: reflection, sharing, gratitude"],
        summary: "Waning Gibbous carries the energy of processing what just reached fullness. It is less about pushing and more about understanding.",
        extra: "This phase often supports teaching, integrating, and deciding what was worth the effort."
      },
      {
        subtitle: "Half-lit again, now decreasing",
        facts: ["Window: last major checkpoint", "Theme: release, editing, rebalancing"],
        summary: "Last Quarter energy is the cleanup phase. It asks what still belongs, what should be cut, and what needs reframing.",
        extra: "This phase is good for endings, repairs, and shedding weight before the next cycle begins."
      },
      {
        subtitle: "The final thin crescent before the next new moon",
        facts: ["Window: last few days of the cycle", "Theme: rest, surrender, closure"],
        summary: "Waning Crescent is the closing exhale of the lunar month. If you meant 'waning crescent,' this is the delicate sliver right before reset.",
        extra: "This phase is usually associated with stillness, sleep, intuition, forgiveness, and letting the cycle end on purpose."
      }
    ],
    planetDays: [
      {
        title: "Sunday",
        facts: ["Ruler: Sun", "Focus: vitality, confidence, visibility"],
        summary: "Sunday is traditionally ruled by the Sun, so it is linked with identity, energy, expression, and being seen.",
        extra: "It is a good symbolic day for warmth, leadership, creativity, and resetting your sense of purpose."
      },
      {
        title: "Monday",
        facts: ["Ruler: Moon", "Focus: emotion, instinct, care"],
        summary: "Monday belongs to the Moon. It tends to carry a softer, more internal atmosphere tied to mood, memory, and home.",
        extra: "It is a good symbolic day for rest, reflection, nurturing, and noticing how you actually feel."
      },
      {
        title: "Tuesday",
        facts: ["Ruler: Mars", "Focus: action, force, courage"],
        summary: "Tuesday is associated with Mars, so it tends to emphasize momentum, assertion, competition, and getting things moving.",
        extra: "It is a good symbolic day for difficult tasks, direct conversations, and disciplined effort."
      },
      {
        title: "Wednesday",
        facts: ["Ruler: Mercury", "Focus: communication, trade, mental speed"],
        summary: "Wednesday belongs to Mercury. It is traditionally linked with language, messages, logistics, learning, and quick decisions.",
        extra: "It is a good symbolic day for meetings, writing, planning, networking, and problem-solving."
      },
      {
        title: "Thursday",
        facts: ["Ruler: Jupiter", "Focus: growth, opportunity, wisdom"],
        summary: "Thursday is associated with Jupiter, which brings themes of expansion, confidence, abundance, and belief.",
        extra: "It is a good symbolic day for bigger plans, generous thinking, teaching, and taking a well-judged leap."
      },
      {
        title: "Friday",
        facts: ["Ruler: Venus", "Focus: pleasure, connection, beauty"],
        summary: "Friday belongs to Venus, so it carries themes of affection, art, harmony, desire, and what feels worth savoring.",
        extra: "It is a good symbolic day for relationships, aesthetics, dating, hospitality, and enjoying what you have."
      },
      {
        title: "Saturday",
        facts: ["Ruler: Saturn", "Focus: discipline, structure, responsibility"],
        summary: "Saturday is traditionally ruled by Saturn. It tends to emphasize boundaries, realism, endurance, and long-term work.",
        extra: "It is a good symbolic day for commitments, repair, systems, and anything that benefits from patience."
      }
    ],
    aspects: {
      conjunction: {
        name: "Conjunction",
        facts: ["Angle: 0°", "Tone: amplified and concentrated"],
        summary: "A conjunction means the current moon sign is sitting on top of your natal sign energy. The feeling is direct, loud, and personal."
      },
      trine: {
        name: "Trine",
        facts: ["Angle: 120°", "Tone: smooth flow and support"],
        summary: "A trine is one of the easier aspects. It suggests the current emotional weather is working with your natural style instead of against it."
      },
      sextile: {
        name: "Sextile",
        facts: ["Angle: 60°", "Tone: helpful opening and cooperation"],
        summary: "A sextile is supportive but lighter than a trine. It usually points to opportunities that reward participation."
      },
      square: {
        name: "Square",
        facts: ["Angle: 90°", "Tone: friction, effort, growth through pressure"],
        summary: "A square creates tension. It is not automatically bad, but it often means the day asks for adjustment, patience, and better choices."
      },
      opposition: {
        name: "Opposition",
        facts: ["Angle: 180°", "Tone: contrast, awareness, balancing polarities"],
        summary: "An opposition can feel like being pulled in two directions. It often reveals what needs balancing between your instincts and the current mood."
      },
      neutral: {
        name: "Neutral",
        facts: ["Angle: no major aspect", "Tone: low drama, light influence"],
        summary: "No major aspect means the moon is not strongly pushing or resisting your natal sign today. The influence is present but softer."
      }
    }
  }
};

const ALMANAC_EN = {
  phase: [
    {label:"New Moon", note:"A reset point in the lunar cycle. Better for intention, quiet starts, and leaving space before things become visible.", yi:"set a clean intention", ji:"overfill the day before it has shape"},
    {label:"Waxing Crescent", note:"The first visible growth after the new moon. Better for testing, starting, and taking the first usable step.", yi:"test a first step", ji:"stay only in planning mode"},
    {label:"First Quarter", note:"A half-lit checkpoint with more friction. Better for deciding, prioritizing, and moving through resistance.", yi:"make a clear decision", ji:"keep circling the same choice"},
    {label:"Waxing Gibbous", note:"The pre-peak refinement phase. Better for editing, improving, and preparing the reveal.", yi:"refine the details", ji:"rush the final pass"},
    {label:"Full Moon", note:"The brightest point of the cycle. Better for seeing results, receiving feedback, and bringing things into view.", yi:"review what is visible", ji:"avoid feedback or overreact to it"},
    {label:"Waning Gibbous", note:"The first release after fullness. Better for reflection, sharing, and deciding what is worth continuing.", yi:"reflect and integrate", ji:"keep adding effort without review"},
    {label:"Last Quarter", note:"A decreasing half moon with cleanup energy. Better for pruning, repairing, and reducing scope.", yi:"cut excess and repair gaps", ji:"start another unnecessary thread"},
    {label:"Waning Crescent", note:"The closing sliver before the next reset. Better for closure, clearing, and leaving quiet space.", yi:"close loops and clear space", ji:"force maximum output"}
  ],
  sign: [
    {label:"Aries", note:"Moon in Aries favors speed, directness, and first moves, but not heat for its own sake.", yi:"move directly", ji:"push from irritation"},
    {label:"Taurus", note:"Moon in Taurus favors steadiness, the body, material reality, and practical calm.", yi:"stabilize the rhythm", ji:"change course impulsively"},
    {label:"Gemini", note:"Moon in Gemini favors messages, information, and light movement, but can scatter attention.", yi:"communicate clearly", ji:"split attention too far"},
    {label:"Cancer", note:"Moon in Cancer favors home, care, memory, and emotional safety.", yi:"care for the inner layer", ji:"hide every feeling until it hardens"},
    {label:"Leo", note:"Moon in Leo favors visibility, creativity, and warm self-expression.", yi:"express the main point", ji:"perform more than the moment needs"},
    {label:"Virgo", note:"Moon in Virgo favors editing, sorting, maintenance, and useful precision.", yi:"organize the details", ji:"get trapped in minor flaws"},
    {label:"Libra", note:"Moon in Libra favors balance, aesthetics, negotiation, and social calibration.", yi:"restore balance through dialogue", ji:"please everyone at your own expense"},
    {label:"Scorpio", note:"Moon in Scorpio favors depth, focus, and seeing what sits under the surface.", yi:"address the real issue", ji:"turn suspicion into certainty"},
    {label:"Sagittarius", note:"Moon in Sagittarius favors perspective, candor, movement, and a wider view.", yi:"look farther ahead", ji:"promise beyond capacity"},
    {label:"Capricorn", note:"Moon in Capricorn favors structure, responsibility, time, and concrete outcomes.", yi:"set the structure", ji:"carry pressure without support"},
    {label:"Aquarius", note:"Moon in Aquarius favors distance, systems thinking, and unconventional solutions.", yi:"reframe the system", ji:"be detached to the point of coldness"},
    {label:"Pisces", note:"Moon in Pisces favors imagination, softness, compassion, and permeability.", yi:"make room for feeling", ji:"let boundaries dissolve"}
  ],
  day: [
    {label:"Sun Day", note:"Sunday carries the cultural symbolism of the Sun: visibility, vitality, and the main thread.", yi:"set the main tone", ji:"scatter energy without a center"},
    {label:"Moon Day", note:"Monday carries the cultural symbolism of the Moon: care, mood, home, and adjustment.", yi:"adjust gently", ji:"push through emotional depletion"},
    {label:"Mars Day", note:"Tuesday carries the cultural symbolism of Mars: action, courage, friction, and clearing obstacles.", yi:"clear a difficult obstacle", ji:"turn tension into conflict"},
    {label:"Mercury Day", note:"Wednesday carries the cultural symbolism of Mercury: language, messages, schedules, and thinking.", yi:"write, speak, and organize", ji:"leave messages ambiguous"},
    {label:"Jupiter Day", note:"Thursday carries the cultural symbolism of Jupiter: growth, learning, opportunity, and long range vision.", yi:"think bigger and plan long", ji:"miss the wider pattern"},
    {label:"Venus Day", note:"Friday carries the cultural symbolism of Venus: relationships, pleasure, beauty, and repair.", yi:"repair tone and relationship", ji:"make the atmosphere harder"},
    {label:"Saturn Day", note:"Saturday carries the cultural symbolism of Saturn: structure, responsibility, patience, and pruning.", yi:"prune and repair", ji:"avoid the responsibility that keeps returning"}
  ],
  west: [
    {yi:"keep ambition realistic", ji:"overpressure yourself"},
    {yi:"preserve independent judgment", ji:"be different only to be different"},
    {yi:"soften while keeping boundaries", ji:"float without direction"},
    {yi:"begin before overthinking", ji:"charge ahead blindly"},
    {yi:"protect resources and pace", ji:"refuse to adapt"},
    {yi:"make the message clear", ji:"open too many threads"},
    {yi:"support emotional safety", ji:"turn small feelings into heavy silence"},
    {yi:"state your center with warmth", ji:"perform for approval"},
    {yi:"make the details useful", ji:"polish until nothing moves"},
    {yi:"negotiate toward balance", ji:"over-adjust for others"},
    {yi:"act after seeing the core", ji:"treat suspicion as proof"},
    {yi:"widen the frame", ji:"promise beyond execution"}
  ],
  chinese: [
    {yi:"notice openings early", ji:"overthink every small signal"},
    {yi:"build through consistency", ji:"move too slowly for the window"},
    {yi:"use courage cleanly", ji:"let impulse outrun judgment"},
    {yi:"keep the atmosphere gentle", ji:"avoid the needed conversation"},
    {yi:"use presence for something real", ji:"overdo the force"},
    {yi:"observe before acting", ji:"test people too much"},
    {yi:"keep useful freedom", ji:"reject every boundary"},
    {yi:"make the environment kinder", ji:"worry yourself into stillness"},
    {yi:"improvise intelligently", ji:"outsmart the simple answer"},
    {yi:"name the standard clearly", ji:"criticize past usefulness"},
    {yi:"protect trust and promises", ji:"become too defensive"},
    {yi:"choose generosity with limits", ji:"relax every boundary"}
  ]
};
